sudo: required
services:
    - docker

before_install:
    - docker build -t hemalshah29/mutli-docker -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true hemalshah29/mutli-docker npm test

after_success:
    - docker build -t hemalshah29/multi-docker-client ./client 
    - docker build -t hemalshah29/multi-docker-nginx ./nginx 
    - docker build -t hemalshah29/multi-docker-server ./server 
    - docker build -t hemalshah29/multi-docker-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push hemalshah29/multi-docker-client
    - docker push hemalshah29/multi-docker-nginx
    - docker push hemalshah29/multi-docker-server
    - docker push hemalshah29/multi-docker-worker